### ISSUE TITLE
Differences from lexorank-ts

### ISSUE THREAD

**Issue by Venryx** [Kayron013/LexoRank#2]
What differences does this package have with the [lexorank-ts](https://github.com/kvandake/lexorank-ts) package?

I ask because I notice that this package has _way_ less code (which is great), but it would be nice to know what features are being given up to achieve that smaller size.

**Comment by Kayron013** [comment]
I didn't study that project before creating this one, but it's much closer to [Jira's model](https://docs.atlassian.com/jira-software/6.6.70/com/atlassian/greenhopper/model/lexorank/LexoRank.html) (which I just discovered).
At a glance, some differences that stand out to me are:
- It has a min and max rank
  - This project specifically avoids a min and max rank
- It has a few different [numeral systems](https://github.com/kvandake/lexorank-ts/tree/master/src/numeralSystems) that utilize different character sets, from 10, 36, and 64 possible characters per digit.
  - Abstracting for this fact is probably a big factor in the larger code size
  - This project only has the 36 character set (0-9, a-z)
- It has decimal ranks
  - Eg. "0|100000:i"
- It seems to want to use 6 integer digit ranks, though you can parse longer strings (probably a bug since using `genNext` on such a rank didn't give me a bigger rank)
  - This project doesn't pad or restrict rank lengths, though ranks ending in `0` aren't allowed

So if you're looking for something most inline with Jira's actual system, you should use `lexorank-ts`. All the features of this project are laid out in the README.

**Comment by Venryx** [comment]
Okay. Thanks much for the comparison!
