### ISSUE TITLE
Question - Rebuilding/Rebalance the rankings

### ISSUE THREAD

**Issue by doug-benn** [Kayron013/LexoRank#3]
Hello,

Not really an issue!

I was just wondering how to impliment rebuilding/rebalancing the ranking of the items. I know the ranks are unbounded so they could just get longer and longer but that will impact a database and preformace at somepoint I guess.

I think JIRA starts moving items into another bucket with a new rank, close to the middle but there isn't much detail on how it is done/what triggers it?

Thank you for any help!
 - Doug

**Comment by Kayron013** [comment]
Your trigger can just be reaching a rank of a certain length. And like you said, you don't have start at the beginning with the new bucket. If the updates need to happen in batches, the buckets keep the migrated and unmigrated records in order. This isn't a perfect implementation, especially starting with a rank value of '1', but I [implemented something](https://github.com/Kayron013/watchlist-bot/blob/main/functions/src/events/normalizeItems.ts) in firebase with a firestore write trigger to check the rank length on writes, then conditionally do some normalization.

Instead of doing the rebalancing as soon as a rank breaches the length max, which could result in multiple writes triggering the rebalancing in succession, you can just update a field somewhere that indicates the max length has been breached, then have a job that periodically checks that field to see if it needs to do the rebalancing.
